const key=document.body.dataset.project,d=window.projectData[key],visuals=window.refinedVisuals[key],depth=window.caseDepth[key],isDevex=key==='devex';document.title=`${d.title} — Michael Dunkelman`;
const nav=`<a class="skip" href="#story">Skip to case study</a><header class="nav"><a class="brand" href="index.html"><b>Michael</b> Dunkelman</a><nav aria-label="Primary"><a href="index.html#work">Work</a><a href="about.html">About</a><a href="Michael-Dunkelman-Resume.pdf">Résumé</a><a href="https://www.linkedin.com/in/michael-dunkelman/">LinkedIn ↗</a></nav></header>`;
const overviewNames=['ddU0F3','XeACp9','s9SUg5','o0Kz7x','x9MPnC','cQ88zQ','8vda5A','qtOlST','e63QM4','H1eYIW'];const sections=d.sections.map((s,n)=>{const figs=visuals[n].map((v,i)=>{const type=overviewNames.some(name=>v.src.includes(name))?'overview':'interface';return `<figure class="evidence evidence-${type}"><header class="evidence-heading"><span>${String(n+1).padStart(2,'0')}.${String(i+1).padStart(2,'0')}</span><h3>${v.title}</h3></header><div class="evidence-frame"><img src="${v.src}" alt="${v.title}" loading="lazy"></div><figcaption>${isDevex?'<strong>Why it mattered</strong>':''}<p>${v.caption}</p></figcaption></figure>`}).join('');return `<section class="story-section reveal" id="chapter-${n+1}" data-chapter="${n+1}"><span class="eyebrow">${s.label}</span><div class="story-copy"><h2>${s.title}</h2><p>${s.body}</p><p>${depth.details[n]}</p><aside class="decision"><span>Design decision</span><p>${s.insight}</p></aside></div><div class="evidence-sequence">${figs}</div></section>`}).join('');
const facts=d.facts.map(f=>`<div class="fact"><span>${f[0]}</span><strong>${f[1]}</strong></div>`).join(''),order=['devex','sso','rbac','oauth','operator'],nextKey=order[(order.indexOf(key)+1)%order.length],next=window.projectData[nextKey];
document.body.innerHTML=nav+`<main><section class="case-hero shell"><span class="eyebrow">${d.order} / ${d.eyebrow}</span><h1>${d.title}</h1><p class="case-dek">${d.dek}</p><div class="case-meta"><div><span>Role</span><strong>${d.role}</strong></div><div><span>Timeframe</span><strong>${d.timeframe}</strong></div><div><span>Partners</span><strong>${d.team}</strong></div></div></section><figure class="case-hero-image"><img src="${d.hero}" alt="${d.title}"></figure><section class="case-summary shell" id="at-a-glance" data-index-section="glance"><div class="summary-grid"><span class="eyebrow">At a glance</span><div class="summary-copy"><h2>The challenge</h2><p>${d.challenge}</p><h2>What I owned</h2><p>${depth.owned}</p><h2>The outcome</h2><p>${d.outcome}</p></div><div class="fact-grid">${facts}</div></div></section><article class="story shell" id="story">${sections}</article><section class="case-conclusion" id="conclusion" data-index-section="conclusion"><div class="shell conclusion-grid"><span class="eyebrow">Project conclusion</span><div class="conclusion-outcome"><span class="conclusion-label">${isDevex?'Delivered outcome':'Shipped result'}</span><h2>${depth.changed}</h2></div><div class="conclusion-reflection"><span class="conclusion-label">What I learned</span><blockquote>${d.close}</blockquote></div><div class="conclusion-limits"><h3>Next steps</h3><p>${depth.limits}</p></div></div></section><section class="next-project"><a class="shell" href="${nextKey}.html"><span class="eyebrow">Next project / ${next.order}</span><h2>${next.title} →</h2></a></section></main><footer class="footer"><div class="shell footer-grid"><span class="eyebrow">Start a conversation</span><h2>Let’s make complex things make sense.</h2><div class="footer-links"><a class="link" href="mailto:mdunkelman@gmail.com">Email me ↗</a><a class="link" href="https://www.linkedin.com/in/michael-dunkelman/">LinkedIn ↗</a></div><span class="footer-mark" aria-hidden="true">MD</span></div></footer>`;
const previewMap={devex:[[2,2],[3,0]],sso:[[3,0],[3,1]],rbac:[[2,0],[3,0]],oauth:[[3,0],[3,1]],operator:[[3,0],[3,1]]};
const previewCards=key==='sso'?`<figure class="final-preview-card final-preview-card-wide"><div class="final-preview-frame"><img class="sso-preview-desktop" src="assets/sso/sso-final-overview.png" alt="SSO connection overview and connection details screens" loading="eager"><div class="sso-preview-mobile"><img src="${visuals[3][0].src}" alt="SSO connection overview" loading="eager"><img src="${visuals[3][1].src}" alt="SSO connection details" loading="eager"></div></div><figcaption><strong>Connection overview and details</strong><p>The finished experience keeps setup status, configuration, and ongoing maintenance in one consistent structure.</p></figcaption></figure>`:previewMap[key].map(([sectionIndex,visualIndex])=>visuals[sectionIndex][visualIndex]).map(v=>`<figure class="final-preview-card"><div class="final-preview-frame"><img src="${v.src}" alt="${v.title}" loading="eager"></div><figcaption><strong>${v.title}</strong><p>${v.caption}</p></figcaption></figure>`).join('');
document.querySelector('.case-hero-image').insertAdjacentHTML('afterend',`<section class="final-preview shell" aria-labelledby="final-preview-title"><header class="final-preview-intro"><span class="eyebrow">${isDevex?'Delivered solution':'Final product'}</span><div><h2 id="final-preview-title">${isDevex?'The Atlas Developer Portal':'Final design'}</h2><p>${isDevex?'One place to discover Atlas, find guidance, understand access requirements, and track onboarding. Select any screen to view it at full resolution.':'A quick look at the finished product.'}</p></div></header><div class="final-preview-grid">${previewCards}</div></section>`);
if(isDevex){
document.querySelector('.final-preview').insertAdjacentHTML('afterend',`<section class="case-arc shell" aria-labelledby="case-arc-title"><header><span class="eyebrow">The story in one view</span><h2 id="case-arc-title">Solving three breaks in the onboarding journey</h2></header><div class="case-arc-grid"><article><small>Problem 01</small><strong>No clear starting point</strong><p>Developers pieced together Jira, Confluence, MkDocs, Slack, and platform-team knowledge.</p></article><i aria-hidden="true"></i><article class="arc-delivered"><small>Problem 02</small><strong>Guidance without a path</strong><p>The portal organized discovery and documentation around what a developer needed to do next.</p></article><i aria-hidden="true"></i><article><small>Problem 03</small><strong>Invisible request progress</strong><p>Jira-backed status became visible so team leaders could understand ownership and progress.</p></article></div></section>`);
const narrativeVisuals=[
`<aside class="story-visual fragmentation-visual" aria-label="The fragmented developer experience before the portal"><header><span>Before the portal</span><strong>One journey, scattered across five places</strong></header><div class="fragment-map"><div class="fragment-center"><b>New Atlas developer</b><span>Where do I start?</span></div><span>Jira<br><small>Requests</small></span><span>Confluence<br><small>Guidance</small></span><span>MkDocs<br><small>Technical docs</small></span><span>Slack<br><small>Human help</small></span><span>Platform teams<br><small>Fulfillment</small></span></div></aside>`,
`<aside class="story-visual ia-visual" aria-label="Comparative research and documentation information architecture"><header><span>Comparative research</span><strong>Studying how mature developer platforms move people from orientation to action</strong></header><div class="benchmark-grid"><div><img src="https://cdn.simpleicons.org/atlassian/1868DB" alt=""><b>Atlassian</b><span>Navigate a broad platform ecosystem</span></div><div><img src="https://cdn.simpleicons.org/stripe/635BFF" alt=""><b>Stripe Docs</b><span>Make technical guidance readable</span></div><div><img src="https://cdn.simpleicons.org/apple/171714" alt=""><b>Apple Developer</b><span>Orient people across tools and capabilities</span></div><div><span class="microsoft-logo" aria-hidden="true"><i></i><i></i><i></i><i></i></span><b>Microsoft Learn</b><span>Structure content into learning paths</span></div><div><img src="https://cdn.simpleicons.org/vercel/171714" alt=""><b>Vercel</b><span>Shorten the path to a first action</span></div></div><div class="benchmark-principles"><b>Principles applied to Atlas</b><ul><li>Orient before exposing complexity</li><li>Organize guidance around developer goals</li><li>Make the next action obvious</li><li>Keep progress and status visible</li></ul></div><div class="ia-divider"><span>From pattern to product structure</span></div><div class="ia-compare"><section><span class="state-label">Ideal structure</span><div class="ia-flow"><b>Documentation</b><i></i><b>Goal-based categories</b><i></i><b>Topic pages</b><i></i><b>Articles</b></div><p>Supports a growing library and helps developers choose content by intent.</p></section><section><span class="state-label">Delivered structure</span><div class="ia-flow ia-flow-short"><b>Documentation</b><i></i><b>Articles in navigation</b></div><p>Fit the small initial library and worked with the existing MkDocs integration.</p></section></div></aside>`,
`<aside class="story-visual scope-visual" aria-label="MVP product decisions"><header><span>MVP decision matrix</span><strong>Match each user problem to a supportable solution</strong></header><div class="scope-grid"><div><span>Experience</span><span>MVP decision</span><span>Why</span><span>Future opportunity</span></div><div><b>Request status</b><em class="kept">Shipped</em><p>Team leaders needed visibility without chasing updates.</p><p>Deeper request management</p></div><div><b>Documentation IA</b><em class="simplified">Simplified</em><p>The library was small and MkDocs integration was complex.</p><p>Categories and topic pages</p></div><div><b>Getting Started</b><em class="deferred">Deferred</em><p>An existing article covered the immediate need.</p><p>Guided onboarding</p></div><div><b>Request form</b><em class="deferred">Deferred</em><p>Validation and backend fulfillment were still evolving.</p><p>Self-service workflow</p></div></div></aside>`,
`<aside class="story-visual future-visual" aria-label="Delivered onboarding foundation and future self-service opportunity"><header><span>What the solution enables</span><strong>A clear foundation now, with room for deeper guidance later</strong></header><div class="future-path"><div><small>Delivered</small><b>Discover</b><span>Understand Atlas and find the right guidance</span></div><i></i><div><small>Delivered</small><b>Request + track</b><span>Use existing Jira workflows with status visibility</span></div><i></i><div><small>Future opportunity · Not designed</small><b>Guided self-service</b><span>Potential direction for registering users, creating teams, assigning roles, and provisioning habitats</span></div></div><footer><span>Solution validated with</span><b>PM</b><b>TPM</b><b>Frontend lead</b><b>Developer author</b><b>Content PM</b></footer></aside>`
];document.querySelectorAll('.story-section').forEach((section,index)=>section.querySelector('.story-copy').insertAdjacentHTML('beforeend',narrativeVisuals[index]));
}
if(key==='sso'){
const ssoVisuals=[
`<aside class="sso-story-visual" aria-label="The fragmented SSO setup journey"><h3>A fragmented setup journey</h3><div class="sso-fragment-flow"><span>Customer</span><i></i><span>Platform operator</span><i></i><div class="sso-fragment-destinations"><b>Legacy tool</b><b>Technical support</b><b>Documentation</b><b>Environment setup</b></div></div><p class="sso-visual-caption">Operators had to connect customer input with several disconnected sources and systems during a live setup process.</p></aside>`,
`<aside class="sso-story-visual" aria-label="The SSO connection mental model"><h3>One connection became the durable organizing object</h3><div class="sso-object-model"><span>Identity provider</span><i></i><strong>SSO connection</strong><i></i><div><small>Connection contains</small><b>Domains</b><b>Mappings</b><b>Organizations</b><b>Metadata</b><b>Environment + status</b></div></div><p class="sso-visual-caption">Treating the connection as a container gave its domains, mappings, organizations, metadata, environment, and status one durable home.</p></aside>`,
`<aside class="sso-story-visual" aria-label="Research findings translated into design principles"><h3>Research findings translated directly into design principles</h3><div class="sso-findings"><div><span>Operators compare fields during live calls</span><i></i><b>Keep configuration visible</b></div><div><span>Technical terms create hesitation</span><i></i><b>Explain fields in context</b></div><div><span>Corrections happen throughout setup</span><i></i><b>Preserve orientation and state</b></div></div><p class="sso-visual-caption">The research favored persistent context and inline guidance over a shorter-looking wizard.</p></aside>`,
`<aside class="sso-story-visual" aria-label="The SSO connection lifecycle"><h3>One model supports the full connection lifecycle</h3><div class="sso-lifecycle"><span><b>01</b>Configure</span><i></i><span><b>02</b>Verify</span><i></i><span><b>03</b>Activate</span><i></i><span><b>04</b>Maintain</span></div><p class="sso-visual-caption">The same structure carries operators from initial configuration through ongoing maintenance, reducing relearning between tasks.</p></aside><aside class="sso-story-visual sso-outcome-chain" aria-label="How the design creates operational value"><h3>From clearer structure to operational value</h3><div><span>Clear connection model</span><i></i><span>Fewer setup ambiguities</span><i></i><span>Faster operator decisions</span><i></i><strong>Lower support burden</strong></div><p class="sso-visual-caption">A clearer operating model helps teams make more confident decisions and rely less on support-led coordination.</p></aside>`
];document.querySelectorAll('.story-section').forEach((section,index)=>section.querySelector('.story-copy').insertAdjacentHTML('beforeend',ssoVisuals[index]));
}
document.querySelector('.footer-links').insertAdjacentHTML('afterend','<p class="footer-note">Michael Dunkelman · Product designer · New York</p>');
window.initResponsiveNav?.();
const shortLabels={devex:['Discover','Envision','Focus','Deliver'],sso:['Understand','Structure','Decide','Deliver'],rbac:['Reframe','Model','Control','Trust'],oauth:['Learn','Correct','Evolve','Ship'],operator:['Define','Scope','Build','Extend']};
const chapterLinks=`<a href="#at-a-glance" data-target="at-a-glance"><span>00</span>At a glance</a>`+d.sections.map((s,n)=>`<a href="#chapter-${n+1}" data-target="chapter-${n+1}"><span>${String(n+1).padStart(2,'0')}</span>${shortLabels[key][n]}</a>`).join('')+`<a href="#conclusion" data-target="conclusion"><span>05</span>Conclusion</a>`;
document.querySelector('#story').insertAdjacentHTML('beforebegin',`<nav class="chapter-nav shell" aria-label="Case study chapters"><button class="chapter-nav-toggle" type="button" aria-expanded="false">On this page</button><div class="chapter-nav-links">${chapterLinks}</div></nav>`);
const chapterNav=document.querySelector('.chapter-nav'),chapterToggle=chapterNav.querySelector('.chapter-nav-toggle'),chapterNavLinks=chapterNav.querySelector('.chapter-nav-links');chapterToggle.addEventListener('click',()=>{const open=chapterToggle.getAttribute('aria-expanded')!=='true';chapterToggle.setAttribute('aria-expanded',String(open));chapterNavLinks.classList.toggle('is-open',open)});chapterNavLinks.addEventListener('click',()=>{chapterToggle.setAttribute('aria-expanded','false');chapterNavLinks.classList.remove('is-open')});
const chapterObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){chapterNav.querySelectorAll('a').forEach(a=>{const active=a.dataset.target===entry.target.id;a.classList.toggle('is-active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}}),{rootMargin:'-25% 0px -65% 0px'});document.querySelectorAll('#at-a-glance,.story-section,#conclusion').forEach(section=>chapterObserver.observe(section));
const updateChapterNavVisibility=()=>{const start=document.querySelector('#at-a-glance').offsetTop-220,end=document.querySelector('#conclusion').offsetTop+document.querySelector('#conclusion').offsetHeight-180;chapterNav.classList.toggle('is-visible',window.scrollY>=start&&window.scrollY<=end)};window.addEventListener('scroll',updateChapterNavVisibility,{passive:true});window.addEventListener('resize',updateChapterNavVisibility);updateChapterNavVisibility();
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.body.insertAdjacentHTML('beforeend',`<dialog class="image-dialog" aria-labelledby="dialog-title"><div class="dialog-inner"><div class="dialog-toolbar"><strong id="dialog-title">Project image</strong><div class="viewer-actions"><button class="zoom-control zoom-out" type="button" aria-label="Zoom out" title="Zoom out">−</button><output class="zoom-level" aria-live="polite">100%</output><button class="zoom-control zoom-in" type="button" aria-label="Zoom in" title="Zoom in">+</button><button class="size-toggle" type="button">View full size</button><button class="dialog-close" type="button" aria-label="Close expanded image">Close ×</button></div></div><div class="dialog-image-wrap"><img class="dialog-image" alt=""></div><p class="dialog-caption"></p></div></dialog>`);
const dialog=document.querySelector('.image-dialog'),wrap=dialog.querySelector('.dialog-image-wrap'),modalImage=dialog.querySelector('.dialog-image'),caption=dialog.querySelector('.dialog-caption'),toggleButton=dialog.querySelector('.size-toggle'),closeButton=dialog.querySelector('.dialog-close'),zoomIn=dialog.querySelector('.zoom-in'),zoomOut=dialog.querySelector('.zoom-out'),zoomLevel=dialog.querySelector('.zoom-level');let returnFocus,fitScale=1,currentScale=1;
const renderSize=()=>{if(!modalImage.naturalWidth)return;modalImage.style.width=`${Math.round(modalImage.naturalWidth*currentScale)}px`;modalImage.style.height='auto';const atFit=currentScale<=fitScale+.001;toggleButton.textContent=atFit?'View full size':'Fit to screen';wrap.classList.toggle('is-full-size',!atFit);zoomLevel.value=`${Math.round(currentScale/fitScale*100)}%`;zoomLevel.textContent=zoomLevel.value;zoomOut.disabled=atFit;zoomIn.disabled=currentScale>=Math.min(3,Math.max(1,fitScale*3))-.001};
const fitImage=()=>{const availableW=Math.max(240,wrap.clientWidth-48),availableH=Math.max(180,wrap.clientHeight-48);fitScale=Math.min(1,availableW/modalImage.naturalWidth,availableH/modalImage.naturalHeight);currentScale=fitScale;renderSize();wrap.scrollTop=0;wrap.scrollLeft=0};
const openImage=img=>{returnFocus=img;const figure=img.closest('.evidence,.final-preview-card'),title=figure?.querySelector('.evidence-heading h3,figcaption strong')?.textContent||d.title,description=figure?.querySelector('figcaption p')?.textContent||'Project overview image';dialog.querySelector('#dialog-title').textContent=title;caption.textContent=description;modalImage.alt=img.alt;document.body.classList.add('dialog-open');dialog.showModal();modalImage.onload=fitImage;modalImage.src=img.currentSrc||img.src;closeButton.focus()};
const setScale=next=>{const oldW=modalImage.clientWidth,oldH=modalImage.clientHeight,centerX=wrap.scrollLeft+wrap.clientWidth/2,centerY=wrap.scrollTop+wrap.clientHeight/2,ratioX=oldW?centerX/oldW:.5,ratioY=oldH?centerY/oldH:.5;currentScale=Math.max(fitScale,Math.min(Math.min(3,Math.max(1,fitScale*3)),next));renderSize();requestAnimationFrame(()=>{wrap.scrollLeft=Math.max(0,modalImage.clientWidth*ratioX-wrap.clientWidth/2);wrap.scrollTop=Math.max(0,modalImage.clientHeight*ratioY-wrap.clientHeight/2)})};
zoomIn.addEventListener('click',()=>setScale(currentScale+fitScale*.25));zoomOut.addEventListener('click',()=>setScale(currentScale-fitScale*.25));toggleButton.addEventListener('click',()=>{if(currentScale<=fitScale+.001)setScale(Math.max(fitScale,1));else fitImage()});closeButton.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>{document.body.classList.remove('dialog-open');modalImage.removeAttribute('src');returnFocus?.focus()});
document.querySelectorAll('.evidence-frame img,.case-hero-image img,.final-preview-frame img').forEach(img=>{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label',`Expand image: ${img.alt}`);img.addEventListener('click',()=>openImage(img));img.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openImage(img)}})});
