window.projectData = {
  devex: {
    order:"01",eyebrow:"Developer experience",title:"Atlas Developer Portal",dek:"Creating one place for developers to discover Atlas, find useful guidance, request access, and understand what happens next.",timeframe:"July–September 2026 · Phase 1",role:"Lead Product Designer · Sole designer",team:"Product · TPM · Frontend and backend engineering · Developer leads · Technical writing",hero:"assets/devex/screens/home-final-tracked.png",
    challenge:"Atlas gives PTC teams a shared cloud-native foundation for building and transitioning products to SaaS, but developers had no reliable starting point for adopting it. Guidance, onboarding requests, ownership, and status were spread across Jira, Confluence, repositories, and the people who knew how the platform worked.",
    outcome:"The first Atlas Developer Portal centralized platform discovery, documentation, access guidance, and Jira request visibility. It made the Atlas landscape easier for new developers to understand while establishing a product foundation for automated self-service onboarding.",
    facts:[["Validation","PM · TPM · Frontend · Content authors"],["Phase 1","Discovery · Docs · Request status"],["Next phase","Automated self-service onboarding"]],
    sections:[
      {label:"01 / Discover",title:"The first problem was knowing where to begin",body:"This was the first Atlas Developer Portal; there was no existing product model to refine. Through developer and stakeholder interviews, I found that new teams had to assemble their own understanding from Jira, Confluence, documentation, and conversations with platform experts. Team leaders also lacked a clear view of where their onboarding requests stood.",insight:"Before automating onboarding, Atlas needed one dependable front door and a visible model of the journey.",images:[1]},
      {label:"02 / Envision",title:"Designing the ideal MVP as one connected journey",body:"I compared Atlassian, Stripe Docs, Apple Developer, Microsoft Learn, and Vercel to understand how mature platforms orient developers, organize technical guidance, and shorten the path to a useful first action. Applying those patterns to Atlas, I connected discovery, guided onboarding, documentation, access requests, and status tracking. The documentation concept organized content by developer goals: categories led to topic collections, then to focused technical articles.",insight:"Designing the complete model first let us reduce scope without losing the relationships the product would need later.",images:[2,3]},
      {label:"03 / Focus",title:"Technical reality changed the shape—not the intent—of Phase 1",body:"Regular reviews with product, engineering, and content authors exposed two important constraints. Documentation lived in a third-party MkDocs site backed by blob storage, and connecting that infrastructure to a richer in-app hierarchy was already complex. At the same time, the onboarding form and fulfillment model were still changing at the backend. Building editable, validated fields in the portal would duplicate uncertain logic and threaten the release.",insight:"The right MVP was not a partial version of every idea. It was the smallest coherent experience the team could support with confidence.",images:[4]},
      {label:"04 / Deliver",title:"Protecting the moments that gave users clarity",body:"For Phase 1, documentation articles were exposed directly in the expanded sidebar—appropriate for the small initial library, although less scalable than the planned category model. We replaced the self-service form with a practical information page that explained prerequisites and linked to existing Jira templates. At stakeholder recommendation, request status remained prominent on the home page so team leaders could see progress without chasing the platform team.",insight:"I paired the reduced scope with explicit future-state agreements so a temporary information architecture would not quietly become permanent.",images:[5,6]}
    ],
    close:"The work reinforced that MVP design is not about showing less ambition. It is about understanding the full system well enough to choose the smallest release that changes the experience in a meaningful way."
  },
  rbac: {
    order: "03", eyebrow: "Platform governance", title: "Scaling role-based access control", dek: "Expanding access without expanding risk, with a model that gave support teams autonomy while preserving platform control.", timeframe: "June–October 2025", role: "Lead designer", team: "Product · Engineering · Design · Tech writing · QA", hero: "assets/rbac/rbac-hero-restored.png",
    challenge: "A small group of Super Admins controlled Operator Center. Routine support work queued behind people with unrestricted access, but opening the application broadly would create security and compliance risk.",
    outcome: "A tiered access model gives Support Admins useful autonomy, lets Super Admins manage operators directly, and records access changes in a searchable audit log.",
    facts: [["Research","7 internal interviews"],["New capabilities","Role UI · Operator management · Audit log"],["Principle","Least privilege"]],
    sections: [
      {label:"01 / Reframe",title:"The problem wasn’t access. It was controlled autonomy.",body:"Seven interviews across Support, Order Fulfillment, Product Management, and Cloud Services revealed different responsibilities but the same dependency on Super Admins. I mapped four operator types and separated the context each needed from actions that created risk.",insight:"The useful question became: what is the smallest set of permissions that lets each person do their job?",images:[1]},
      {label:"02 / Model",title:"Designing permissions around responsibility",body:"The model defined Support, Provisioning, and Super Admin access. Restricted roles retained organization, license, and SSO context while high-consequence controls were removed or disabled. Clear navigation and role descriptions made those boundaries understandable.",insight:"Least privilege still had to provide enough context to resolve the support issue.",images:[2,3]},
      {label:"03 / Control",title:"Role management without engineering tickets",body:"A centralized operator table shows people, roles, and metadata in one place. Add, edit, and remove dialogs keep the operator visible, explain the authority being granted, and distinguish reversible edits from destructive changes.",insight:"Changing another person’s authority deserved stronger safeguards than viewing sensitive context.",images:[4]},
      {label:"04 / Trust",title:"Making delegated access auditable",body:"The Audit Logs page makes every role and access change traceable. Super Admins can filter six months of activity, download displayed results, and inspect the action, affected object, actor, timestamp, and success or failure status.",insight:"Delegation becomes trustworthy when the system can explain its history as clearly as it enforces access.",images:[5]}
    ],
    close: "The key lesson was that useful access is not the same as broad access. Support teams needed enough context to investigate problems, while the system still had to make authority and accountability explicit."
  },
  sso: {
    order:"02",eyebrow:"Identity & access",title:"Single Sign-on Connection Manager",dek:"Turning a fragmented, support-led SSO setup process into a guided operational workflow.",timeframe:"October 2023–April 2024",role:"Lead designer",team:"Product · Engineering · Design · Tech writing · QA",hero:"assets/sso/ZHjS5OHZey9CJHKIv6fivQW80E.png",
    challenge:"SSO configuration lived in an aging tool with limited fields, limited customization, and no path toward customer-led administration. Internal operators coordinated technical information across customers and support teams, often while configuring a connection live.",
    outcome:"PTC operators can now create, inspect, refresh, and modify SSO connections from one modern interface inside Operator Center.",
    facts:[["Primary user","PTC platform operators"],["Core object","SSO connection"],["Environment","Dev · Staging · Production"]],
    sections:[
      {label:"01 / Understand",title:"One configuration, many moving parts",body:"Interviews with the operators doing live customer setup helped me map coordination among customers, technical support, identity providers, and PTC’s development, staging, and production environments. The workflow exposed a key information-design problem: related domains, metadata, mappings, organizations, and status had no durable home.",insight:"The design needed to reduce coordination cost without pretending the underlying configuration was simple.",images:[1,2,3]},
      {label:"02 / Structure",title:"Giving the feature a clear home and object model",body:"I audited the legacy Vuforia tool and worked with product and engineering to define the information architecture. The SSO Manager became a dedicated Operator Center page, while a connection, rather than an individual domain, became the organizing object for federated domains and configuration data.",insight:"Choosing the right object model removed more complexity than any individual component or interaction could.",images:[4,5,6]},
      {label:"03 / Decide",title:"Why the long form stayed long",body:"A multi-step wizard initially appeared cleaner, but operators configure SSO live with customers and repeatedly cross-reference fields. Hiding sections behind steps increased memory load and made correction slower. The final long form preserved context while sectioning, progressive help, and hierarchy reduced scanning cost.",insight:"A shorter-looking interface was not a simpler workflow. The deliberate choice was visibility over cosmetic minimalism.",images:[7,8,9]},
      {label:"04 / Deliver",title:"A consistent path from creation to maintenance",body:"The details page mirrors the creation structure so operators do not relearn the information model after setup. Status, refresh, editing, and deletion sit beside the configuration they affect. Launch feedback confirmed that operators could move between creation and maintenance without returning to legacy documentation for orientation.",insight:"Using the same structure helps operators move among setup, diagnosis, and maintenance.",images:[10,11,12]}
    ],close:"The wizard looked simpler, but it made the real task harder. Keeping the complete form visible gave operators the context they needed to compare, correct, and maintain technical information with customers."
  },
  oauth: {
    order:"04",eyebrow:"Integration management",title:"OAuth 2.0 Client Integration Manager",dek:"Helping Windchill administrators connect third-party systems securely without turning OAuth into a documentation exercise.",timeframe:"July–October 2023",role:"Lead designer",team:"Product · Engineering · Design · Tech writing",hero:"assets/oauth/xCfRTpz9RXLepb7TN0VgU1bNRBM.svg",
    challenge:"Windchill customers needed PLM data inside ERP and analytics tools, but PTC lacked a customer-managed path for creating and maintaining secure OAuth 2.0 clients.",
    outcome:"Windchill+ administrators can configure OAuth integrations in Admin Center, rotate secrets, edit callback URLs, and copy the credentials needed by third-party applications.",
    facts:[["Protocol","OAuth 2.0"],["Audience","Windchill+ administrators"],["Core actions","Configure · Rotate · Maintain"]],
    sections:[
      {label:"01 / Learn",title:"Designing a technical tool required technical fluency",body:"I mapped the journeys of both application users and Windchill administrators, audited comparable integration tools, and built a protocol diagram with engineering. Learning the OAuth exchange in detail let me distinguish system mechanics from the decisions an administrator actually needed to make.",insight:"Technical fluency was not extra research; it was necessary to simplify responsibly.",images:[1,2,3,4]},
      {label:"02 / Correct",title:"The pivotal assumption was wrong",body:"Early concepts centered the secret key because it appeared to be the most important credential. Review with engineering revealed that Client IDs were the durable link between customer applications, while secrets rotated around them. I restructured the interface around client applications and their IDs.",insight:"Correcting the mental model early prevented a polished interface from reinforcing the wrong concept.",images:[5,6,7,8]},
      {label:"03 / Evolve",title:"Three iterations clarified the management model",body:"The design progressed from basic key rotation, to a secret-management table, to dedicated Auth0 application pages. Feedback from product and engineering tested not only the interaction but the object model behind it. Each iteration made the relationship among applications, Client IDs, callback URLs, and secrets more explicit.",insight:"The work converged when the page structure matched the lifecycle of an integration, not the shape of the backend response.",images:[9,10,11,12]},
      {label:"04 / Ship",title:"Two pages, one understandable system",body:"The overview supports scanning and comparison across clients. The individual page concentrates callback URLs, Client ID, secret rotation, and configuration actions around one integration. Copy and status treatments explain which values are stable, which are sensitive, and what changes when a secret rotates.",insight:"Two purpose-built views proved clearer than forcing overview and credential management into one dense table.",images:[13,14,15,16]}
    ],close:"The turning point was correcting the product model, not polishing the first interface. Once the team aligned around applications and durable Client IDs, the screen structure became much clearer."
  },
  operator: {
    order:"05",eyebrow:"Administration platform",title:"PTC Operator Center",dek:"Creating one operating surface for the organizations, users, and licenses behind PTC’s SaaS products.",timeframe:"2023–ongoing",role:"Lead designer",team:"Product · Engineering · Design · Tech writing",hero:"assets/operator/zOfNEeyRbBbDdB4yw3zRSI74t4.svg",
    challenge:"Product teams managed customers through fragmented, product-specific processes. As Creo and Windchill moved toward SaaS, the legacy tooling could not support their more complex organization and licensing needs.",
    outcome:"Authorized employees now use a centralized application to locate organizations, update metadata, troubleshoot users and licenses, and create new customer organizations.",
    facts:[["Initial scope","Organizations · All users"],["Platform","PTC Atlas"],["Design approach","Reusable admin patterns"]],
    sections:[
      {label:"01 / Define",title:"A platform problem disguised as a fulfillment problem",body:"Stakeholder research showed that licensing was only one part of a larger organization lifecycle. I synthesized jobs across fulfillment, support, and product operations into a needs matrix that captured each role’s goals, identifiers, decisions, and dependencies.",insight:"The matrix exposed shared responsibilities across teams and the points where a single generic workflow would fail them.",images:[1,2,3]},
      {label:"02 / Scope",title:"Choosing a useful MVP without designing a dead end",body:"The opportunity covered organizations, users, licensing, SSO, provisioning, and permissions, but the first release needed a useful core. I prioritized Organizations and All Users because they supported the most common lookup and troubleshooting jobs, then designed an information architecture that could absorb later capabilities.",insight:"The MVP was intentionally narrow in features but broad enough in architecture to avoid another isolated internal tool.",images:[4,5,6]},
      {label:"03 / Build",title:"Dense tables, deliberate information",body:"The Organizations page balances scanning at scale with direct access to details. I selected customer number, organization ID, status, and dates because they match the identifiers operators use across systems, rather than because they were simply available from the API. Search, sorting, and row hierarchy reflect real investigation behavior.",insight:"Enterprise density becomes usable when every field earns its place through a decision someone needs to make.",images:[7,8,9]},
      {label:"04 / Extend",title:"A reusable foundation for operational workflows",body:"Create-organization, create-license, user lookup, and troubleshooting flows reuse a small set of table, detail, form, and status patterns. Working near engineering ensured those patterns matched the platform’s states and could be implemented consistently. Later SSO and role-based access work could therefore join the same product instead of becoming separate tools.",insight:"The lasting result is a shared operating model, not a set of disconnected screens.",images:[10,11,12,13]}
    ],close:"A narrow MVP did not have to become another isolated tool. By defining the relationships among organizations, users, and future capabilities early, the first release could solve immediate work and still leave room to grow."
  }
};
