const refinedStyle=document.createElement('link');refinedStyle.rel='stylesheet';refinedStyle.href='v4.css';document.head.appendChild(refinedStyle);const projectStyle=document.createElement('link');projectStyle.rel='stylesheet';projectStyle.href='v4-projects.css';document.head.appendChild(projectStyle);const v5Style=document.createElement('link');v5Style.rel='stylesheet';v5Style.href='v5.css';document.head.appendChild(v5Style);const v6Style=document.createElement('link');v6Style.rel='stylesheet';v6Style.href='v6.css';document.head.appendChild(v6Style);const v7Style=document.createElement('link');v7Style.rel='stylesheet';v7Style.href='v7.css';document.head.appendChild(v7Style);const v8Style=document.createElement('link');v8Style.rel='stylesheet';v8Style.href='v8.css';document.head.appendChild(v8Style);const headerContact=document.querySelector('.nav nav a:last-child');if(headerContact){headerContact.href='https://www.linkedin.com/in/michael-dunkelman/';headerContact.textContent='LinkedIn ↗'}
const v9Style=document.createElement('link');v9Style.rel='stylesheet';v9Style.href='v9.css';document.head.appendChild(v9Style);
const v10Style=document.createElement('link');v10Style.rel='stylesheet';v10Style.href='v10.css';document.head.appendChild(v10Style);
const v11Style=document.createElement('link');v11Style.rel='stylesheet';v11Style.href='v11.css';document.head.appendChild(v11Style);
const v12Style=document.createElement('link');v12Style.rel='stylesheet';v12Style.href='v12.css';document.head.appendChild(v12Style);
const v13Style=document.createElement('link');v13Style.rel='stylesheet';v13Style.href='v13.css';document.head.appendChild(v13Style);
const staticFooter=document.querySelector('.footer');if(staticFooter){staticFooter.querySelector('h2').textContent='Let’s make complex things make sense.';if(!staticFooter.querySelector('.footer-note'))staticFooter.querySelector('.footer-links').insertAdjacentHTML('afterend','<p class="footer-note">Michael Dunkelman · Product designer · New York</p>')}
window.initResponsiveNav=()=>{const header=document.querySelector('.nav'),nav=header?.querySelector('nav');if(!header||!nav||header.querySelector('.nav-toggle'))return;nav.id='primary-nav';const button=document.createElement('button');button.className='nav-toggle';button.type='button';button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls','primary-nav');button.textContent='Menu';header.insertBefore(button,nav);const close=()=>{button.setAttribute('aria-expanded','false');nav.classList.remove('is-open')};button.addEventListener('click',()=>{const open=button.getAttribute('aria-expanded')!=='true';button.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open);if(open)nav.querySelector('a')?.focus()});nav.addEventListener('click',e=>{if(e.target.closest('a'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('is-open')){close();button.focus()}});document.addEventListener('click',e=>{if(nav.classList.contains('is-open')&&!header.contains(e.target))close()})};
window.initResponsiveNav();
const V=(src,title,caption)=>({src,title,caption});
window.refinedVisuals={
rbac:[
[V('assets/rbac/ddU0F3fb4cJeTc46vSj7nDunU.png','Mapping responsibilities before permissions','The needs model separates information required for support from authority that could change the system.')],
[V('assets/rbac/79B6hIeZfUUbC4c0mNiJ2YsQ4gk.png','Support Operator experience','Read-only organization context remains visible while high-consequence actions are removed or disabled.'),V('assets/rbac/m1PLbZOKqIU5wjbF3bKpoITGc.png','View-only SSO configuration','Support can inspect customer SSO context without receiving controls that could affect authentication for thousands of users.')],
[V('assets/rbac/O8BD3fK7U8e4Tonz4Hpx1QCzA.png','Operator management and role changes','The table and focused dialogs let Super Admins assign, edit, or remove access without leaving context.')],
[V('assets/rbac/audit-log.png','Searchable audit history','The log exposes activity, affected objects, actors, timestamps, and status, with filters and export for investigation and compliance.')]],
sso:[
[V('assets/sso/s9SUg5mX1shakMpEzwobkz8S8.png','High-level setup journey','The journey maps handoffs among customers, platform operators, and administrators.'),V('assets/sso/o0Kz7x2nAqH5oF4jQKW02quQqyU.jpg','Coordination across environments','The broader workflow shows why operators needed to track one configuration across three environments.')],
[V('assets/sso/0tHAmJCJSUqzC3rSZAL8CmfCFfw.png','Legacy configuration tool','The existing experience fragmented related connection data across fields and domains.'),V('assets/sso/x9MPnCgd6uyYOhCVwEa94QsXO8.jpg','Connection-centered architecture','The revised model makes the connection the durable object containing domains, mappings, organizations, metadata, and status.')],
[V('assets/sso/9Ved0ityBm64Y4Z7mrBAcUt7bk0.png','Testing the complete configuration form','Review identified where operators needed persistent context, field guidance, and clearer grouping.'),V('assets/sso/97xHDIgrrG6TtWDJQ08ATl5cWI.png','Creation and maintenance states','The workflow preserves one information model through setup, refresh, editing, and deletion.')],
[V('assets/sso/BfcCyA5LQJHlUvjrnhETGYxM.svg','Final connection overview','The management view makes environment and status scannable before operators open details.'),V('assets/sso/bU5qdlsTTHuwH6eGeiaIRydmf0.svg','Final connection details','Creation and details share the same structure, reducing relearning during maintenance.')]],
oauth:[
[V('assets/oauth/cQ88zQAzCedn66LkAqwdfrvUAjY.png','Administrator and application journey','The journey separates what administrators configure from what application users experience.'),V('assets/oauth/8vda5ABnnXaD9pBSjTFQuXOxMA.png','OAuth authentication model','Protocol mapping clarified which mechanics needed to be visible and which could stay behind the interface.')],
[V('assets/oauth/qtOlSTBvIgMaLtoDtfZcAB1iWCs.png','Early credential-centered model','Initial concepts overemphasized secrets even though they rotate around durable Client IDs.'),V('assets/oauth/K0w0RIRfH7ptBrssDmJY06UcGA.png','Restructuring around applications','The revised view organizes credentials and callbacks around the application being integrated.')],
[V('assets/oauth/dMGNIjXwPxlFmn5IAfMnUqhmJ4o.png','Evolving the management model','Iterations moved from key rotation toward a persistent application lifecycle.')],
[V('assets/oauth/38tuGZsGwyATwHy9vQLDbIpLpA.svg','Client overview','The overview supports comparison without exposing sensitive credentials unnecessarily.'),V('assets/oauth/951hgUJV77ShHt86GxYmgHrBuI.svg','Application details','Client ID, callback URLs, secret rotation, and actions live in one understandable lifecycle.')]],
operator:[
[V('assets/operator/e63QM4awKydR1VtH140uFmB1U8.jpg','Cross-functional needs matrix','The matrix compares fulfillment, support, and product-operations needs to reveal shared jobs and meaningful differences.')],
[V('assets/operator/H1eYIWSBCT8UVATrXqlJf562Kd8.svg','Scoping the operating model','The original planning artifact connects prioritized operator needs to an information model that could later absorb licensing, SSO, and permissions.')],
[V('assets/operator/okmBIGuXfzwVZVmPZ21h5EG244.png','Comparing organization states','Explorations test which identifiers, statuses, and actions operators need while scanning at scale.'),V('assets/operator/4rg0F4zsGpYkC5m6pElbnn7CW5w.png','Core organization workflows','Creation, inspection, and update reuse patterns while preserving high-consequence context.')],
[V('assets/operator/zXKsZ4Fis6WXnSRrws2XYen0.svg','Reusable operational patterns','The system establishes table, form, detail, and status patterns later capabilities can inherit.'),V('assets/operator/Uj931TLJYWsHe2MiKQ867GW5XU.svg','One operating surface','Organizations, users, and administrative work now live in a consistent product rather than fragmented tools.')]]};
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
window.caseDepth={
sso:{owned:'I led the experience from discovery through delivery: interviewing platform operators, mapping the existing workflow, defining the connection-centered information model, designing creation and maintenance flows, and partnering with product, engineering, QA, and technical writing through implementation.',details:['The legacy Vuforia tool reflected a narrow configuration model that could not support the fields, customization, and lifecycle required by newer SaaS products. Because operators often configured SSO while speaking with customers, delays and ambiguity became visible in real time. I mapped who supplied each piece of information, where handoffs occurred, and where operators lost confidence.','I tested several organizing models with product and engineering. Treating each domain as the primary object matched parts of the backend but scattered what operators understood as one setup. A connection created a stable container for domains, mappings, organizations, metadata, environment, and status. The same structure could eventually support customer self-service.','A wizard initially appeared more approachable, but it hid fields operators needed to compare while customers read or corrected values. Operators needed to compare information more than they needed a shorter-looking form. The complete form remained, while hierarchy, sectioning, field guidance, validation, and technical writing made its density navigable.','Creation was only the beginning. I aligned overview, details, refresh, editing, and deletion around one vocabulary and section structure, then worked through states and edge cases with engineering and QA. Operators therefore did not have to relearn the model when returning to maintain a connection.'],changed:'Operators gained one modern place to create, inspect, refresh, and maintain SSO connections across development, staging, and production. The connection model also gave the team a foundation for future customer-led configuration.',limits:'Extend the model to customer permissions, automation, and self-service setup as the supporting platform capabilities become available.'},
rbac:{owned:'I led research synthesis, permission-model definition, information architecture, operator-management workflows, and audit-log design. I partnered with product and engineering from feasibility through delivery and worked through role states and edge cases with QA and technical writing.',details:['I translated recurring jobs into four operator profiles, then compared what each person needed to see, change, and escalate. That tied interview evidence directly to the access model instead of treating every new user as one broad role or mirroring the existing organizational chart.','Backend permissions were not yet fully dynamic. I aligned the model to feasible controls, preserving read-only organization, license, and SSO context while constraining provisioning and configuration actions. Role-specific navigation and disabled states gave Support enough information to investigate safely without implying authority they did not have.','Super Admins previously needed engineering to change access. I designed one management surface and tested add, edit, and remove states with product and engineering. Inline role descriptions clarified scope before commitment, while stronger confirmation was reserved for changes that could materially expand or remove another operator’s authority.','The log defaults to 30 days while supporting six months of filtered history. I organized columns around investigator questions: what happened, what changed, who acted, when, and whether it succeeded. Per-column filtering keeps dense activity searchable, while downloading displayed results supports deeper compliance review without overloading the primary table.'],changed:'Support teams gained useful autonomy without unrestricted power. Super Admins can manage operators in-product, and access changes now have a visible, searchable history.',limits:'Connect the role model to dynamic API-level permissions, then explore customer-managed custom roles.'},
oauth:{owned:'I owned journey mapping, competitive and technical research, the interaction model, and the evolution from credential management to application-centered administration. I worked closely with engineering to validate the OAuth model and with product to define a supportable release.',details:['Two audiences shaped the experience: administrators configuring integrations and application users authorizing access. I mapped both journeys and created a protocol diagram with engineering so the interface would simplify the right concepts rather than conceal information required for safe administration.','Early concepts centered the secret because it appeared to be the most consequential credential. Engineering review exposed the flaw: Client IDs are the durable link to an application, while secrets rotate around that identity. I changed the information architecture instead of polishing the original assumption.','Three major iterations moved from basic key rotation, to a secret-management table, to dedicated application pages. I evaluated sensitive-value visibility, recovery from rotation, callback URL maintenance, and the relationship between overview and details at every stage.','The overview supports orientation across clients, while the detail page concentrates Client ID, callback URLs, secret rotation, and configuration actions around one application. Content and status treatments distinguish stable identifiers from sensitive, changeable credentials.'],changed:'The project established a customer-manageable path for secure integrations and aligned product, design, and engineering around a shared understanding of OAuth that can extend to additional SaaS products.',limits:'Measure adoption and support volume as more customers configure and maintain OAuth integrations.'},
operator:{owned:'I led research synthesis, MVP definition, information architecture, organization and user workflows, and the reusable patterns that became the platform foundation. I partnered with product and engineering to balance immediate fulfillment needs with a system that could grow.',details:['As Creo and Windchill moved toward SaaS, teams managed customers through fragmented product-specific processes. I created a needs matrix across fulfillment, support, and product operations to expose shared jobs, distinct responsibilities, and the identifiers people used across systems.','The opportunity included organizations, users, licenses, SSO, provisioning, and permissions. I prioritized Organizations and All Users because they supported the most common lookup and troubleshooting work, while designing relationships and navigation that could absorb deferred capabilities later.','Dense tables were necessary, but every field needed to support a decision. Customer number, organization ID, status, and dates match how operators reconcile information across systems. Search, sorting, and hierarchy reflect investigation behavior rather than API convenience.','Create-organization, licensing, user lookup, and troubleshooting flows reuse a compact set of patterns. Staying close to engineering ensured those patterns matched real platform states and allowed later SSO and RBAC capabilities to join one product.'],changed:'Authorized employees gained one operating surface for finding organizations, troubleshooting users and licenses, and creating customer organizations. It also became the foundation for the other work in this portfolio.',limits:'Extend the shared patterns into the deferred licensing, provisioning, and permission workflows.'}}
